name: 'pkgr/action/package'
description: 'Package your application as DEB or RPM'
inputs:
  target:
    description: 'Distribution to target (e.g. debian/13, ubuntu/24.04, el/9)'
    required: true
  name:
    description: 'Name of the package'
    required: true
    default: ${{ github.repository }}
  path:
    description: 'Path to the application'
    required: true
    default: '${{ github.workspace }}'
  version:
    description: 'Version of the package'
    required: true
    default: '0.0.0'
  pkgr_version:
    description: 'Version of pkgr'
    required: true
    default: 'master'
  cache_prefix:
    description: 'Prefix for the cache'
    required: true
    default: 'v1'
  env:
    description: 'Environment variables to pass to pkgr'
    required: false
    default: ''
  debug:
    description: 'Debug mode'
    required: false
    default: 'false'

outputs:
  workspace:
    description: "Workspace directory"
  package_path:
    description: "Package file path"
  package_type:
    description: "Package type"
  package_name:
    description: "Package name"

runs:
  using: 'node24'
  main: 'dist/index.js'
