name: Test
on: [push]

jobs:
  test:
    timeout-minutes: 10
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - debian:10
          - debian:11
          - debian:12
          - ubuntu:20.04
          - ubuntu:22.04
          - ubuntu:24.04
          - el:7
          - el:8
          - el:9
          - sles:12
          - sles:15

    steps:
      - uses: actions/checkout@v4
        with:
          path: action
      - uses: actions/checkout@v4
        with:
          repository: crohr/blank-sinatra-app
          ref: master
          path: app
      - uses: ./action/package
        id: package
        with:
          name: blank-sinatra-app
          target: ${{ matrix.target }}
          version: '1.0.0'
          path: app
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.package_name }}
          path: ${{ steps.package.outputs.package_path }}