name: Test
on:
  push:
  workflow_dispatch:

env:
  REPOSITORY: crohr/blank-noop-app
jobs:
  test:
    timeout-minutes: 30
    name: ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - debian:13
          - ubuntu:24.04
          - el:9
          - sles:15

    steps:
      - uses: actions/checkout@v5
        with:
          path: action
      - uses: actions/checkout@v5
        with:
          repository: ${{ env.REPOSITORY }}
          ref: master
          path: app
      - uses: ./action/package
        id: package
        with:
          target: ${{ matrix.target }}
          name: blank-noop-app
          version: '1.0.0'
          path: app
          debug: true
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.package_name }}
          path: ${{ steps.package.outputs.package_path }}
      - name: Publish
        uses: ./action/publish
        with:
          target: ${{ matrix.target }}
          token: ${{ secrets.PACKAGER_PUBLISH_TOKEN }}
          repository: ${{ env.REPOSITORY }}
          channel: ${{ github.ref_name }}
          file: ${{ steps.package.outputs.package_path }}
